config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments, except: [:new, :index]
  end
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :body, presence: true
  after_commit :create_notifications, on: :create
  broadcasts_to :article
  private
    def create_notifications
      Notification.create do |notification|
        notification.notify_type = 'article'
        notification.actor = self.user
        notification.user = self.article.user
        notification.target = self
        notification.second_target = self.article
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article, only: [:index, :edit, :update, :create ]
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update, :destroy, :new, :create]
  before_action only: [:edit, :update, :destroy] do
    authorize_user(@comment.user)
  end

  def index
    @comments = @article.comments
  end

  def edit; end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to article_path(@article), notice: "Comment updated successfully" }
      else
        flash[:alert] = @comment.errors.full_messages
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def create
    @comment = @article.comments.create(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path(@article) }
      else
        format.html { redirect_to @article, alert: @comment.errors.full_messages }
      end
    end
  end

  def show
    redirect_to article_path(Article.find(params[:article_id]))
  end

  def destroy
    respond_to do |format|
      if @comment.destroy
        format.html { redirect_to article_path(Article.find(params[:article_id])) }
      end
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def set_article
      @article = Article.find(params[:article_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <%= simple_format(comment.body) %>
</div>

app/views/comments/_comments.html.erb
<div class="row">
  <% comments.each do |comment| %>
    <% if comment.body %>
      <div class="col-sm-10">
        <%= simple_format(comment.body) %>
      </div>
      <div class="col-sm-2">
          <% if logged_in? && current_user == comment.user %>
            <%= link_to '', edit_article_comment_path( comment.article_id,comment.id ), class: 'btn btn-info btn-xs glyphicon glyphicon-edit' %>
            <%= link_to "", article_comment_path(comment.article_id ,comment.id), method: :delete, class: 'btn btn-danger glyphicon glyphicon-trash btn-xs' %>
          <% end %>
        <br/>
      </div>
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @comment], :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <%= f.text_area :body, class: "form-control", placeholder: "Add a Comment", autofocus: true %>
  <%= f.submit class: 'btn btn-success btn-xs' %>
<% end %>

app/views/comments/edit.html.erb
<%= render 'comments/form'%>