config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments, except: [:new, :index]
  end
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5, maxmum: 100}
  validates :description, presence: true, length: {minimum: 5}
  validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user, only:[:new, :create, :edit, :update, :destroy]
  before_action only: [:edit, :update, :destroy] do
    authorize_user(@article.user)
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_path(@article), notice: "Article was successfully created!" }
      else
        flash[:alert] = @article.errors.full_messages
        format.html { render 'new', status: :unprocessable_entity }
      end
    end
  end

  def show
    @comment = Comment.new
    @comments = @article.comments
  end

  def edit; end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_path(@article), notice: "Article was updated!" }
      else
        flash[:alert] = @article.errors.full_messages
        format.html { render 'edit', status: :unprocessable_entity }
      end
    end
  end

  def index
    @pagy, @articles = pagy(Article.all)
  end

  def destroy
    respond_to do |format|
      @article.destroy
      format.html { redirect_to articles_path, notice: "Article was deleted" }
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :description, :user_id)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/views/articles/_form.html.erb
<div class="row">
 <div class="col-xs-12">
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :title %>
   </div>
   <div class="col-sm-8">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
   </div>
  </div>
  <div class="form-group">
   <div class="control-label col-sm-2">
    <%= f.label :description %>
   </div>
   <div class="col-sm-8">
    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
   </div>
  </div>
  <div class="form-group">
   <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit class: 'btn btn-success btn-large' %> | 
    <%= link_to 'Back', articles_path , class: 'btn btn-warning btn-large'%>
   </div>
  </div>
<% end %>
 </div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<%= render 'shared/article', obj: @articles %>
<div align="center">
  <%= raw pagy_bootstrap_nav(@pagy) %>
</div>

app/views/articles/new.html.erb
<h1 align="center">Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<% turbo_stream_from @article %>
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row" align="center">
        <div class="col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <div class="article-actions">
    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
    <%= link_to "delete", article_path(@article), method: :delete, data: { confirm: "are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    <%= link_to "Back", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description"><strong>Comments:</strong></h4>
  <%= render 'comments/form' if logged_in? %>
  <hr>
  <%= render 'comments/comments', comments: @comments %>
</div>