config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments, except: [:new, :index]
  end
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
end

app/views/shared/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %><br/>
          <div class="article-meta-details">
            <small>Created by: <%= article.user.username if article.user %>,
              <%= time_ago_in_words(article.created_at) %> ago,
              last updated: <%= time_ago_in_words(article.updated_at) %> ago
            </small>
          </div>
        </div>
        <div class="article-actions">
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this obj from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg|%>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
  <% flash.each do |key, value| %>
    <div class="alert <%= bootstrap_class_for(key.to_s.sub('_stay', '')) %> alert-dismissible show">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <% if value.is_a?(Array) %>
        <ul>
          <% value.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% else %>
        <%= raw value %>
      <% end %>
    </div>
  <% end %>
</div>
</div>